[build]
builder = "maven"
buildCommand = "mvn clean package"

[deploy]
startCommand = "java -jar target/Rello-Boot.jar"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[env]
PORT = "9992" 